global:
  scrape_interval: 15s  # 기본 스크랩 간격 (15초)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']

  - job_name: 'prefect'
    static_configs:
      - targets: ['prefect:4200']
